### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by yofukashino** [romdotdog/wpm#3] opened 2022-05-26 00:40 UTC
starts in hundred and then goes to zero slowly even if i am typing

**Comment by romdotdog** [comment] 2022-05-26 03:20
I can't reproduce. When you're typing, are you using spaces to separate words?

**Comment by yofukashino** [comment] 2022-05-26 21:43
> I can't reproduce. When you're typing, are you using spaces to separate words?

who dont?

**Comment by yofukashino** [comment] 2022-05-26 21:44
but shouldnt it go to zero even if am not typing? like can you add a check interval to it, so that it wouldnt just depend on user typing but keep checking itself idk,

**Comment by romdotdog** [comment] 2022-05-26 21:53
Why would it update your WPM when you're not typing? You wouldn't get a chance to see your true WPM.

**Comment by yofukashino** [comment] 2022-05-28 04:48
It should reduce by time if not typing because it's how you measure wpm else it's not live wpm

**Comment by romdotdog** [comment] 2022-05-29 16:42
This is what the plugin does already. I'm closing this issue because I don't see a bug. Feel free to create a fork based on your desired changes.

**Closed as completed by romdotdog** 2022-05-29 16:42 UTC
